JSON_EXTENSION = ".json"

DEFAULT_HOST = "127.0.0.1"
BUFFER_SIZE = 4096
DEFAULT_TIMEOUT = 3

RESOLVER_DEFAULT_PORT = 5300
ROOT_DEFAULT_PORT = 5301
TLD_DEFAULT_PORT = 5302
AUTHORITATIVE_DEFAULT_PORT = 5303

DEFAULT_ZONES_DIR = "data/zones"
DEFAULT_ROOT_CONFIG_PATH = "data/root.json"
DEFAULT_TLD_CONFIG_PATH = "data/tld.json"
